# Generated by Django 5.1.4 on 2024-12-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Укажите адрес компании', max_length=100, verbose_name='Адрес')),
                ('phone_number', models.CharField(help_text='Укажите номер телефона компании', max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(help_text='Укажите электронную почту компании', verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='MedicalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_services', models.CharField(help_text='Укажите название медицинской услуги', max_length=200, verbose_name='Название медицинской услуги')),
                ('description', models.TextField(help_text='Введите описание медицинской услуги', verbose_name='Описание медицинской услуги')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену медицинской услуги', max_digits=10, verbose_name='Цена медицинской услуги')),
            ],
            options={
                'verbose_name': 'Медицинская услуга',
                'verbose_name_plural': 'Медицинские услуги',
            },
        ),
    ]
