# Generated by Django 5.1.4 on 2024-12-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_patientcontacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
