# Generated by Django 5.1.4 on 2024-12-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(help_text='Укажите название компании', max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(help_text='Введите описание компании', verbose_name='Описание компании')),
                ('address', models.CharField(help_text='Укажите адрес компании', max_length=100, verbose_name='Адрес')),
                ('phone_number', models.CharField(help_text='Укажите номер телефона компании', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(help_text='Укажите электронную почту компании', max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
